### PR TITLE
Mantine select group

### PR DESCRIPTION
**Pull request by dubbofeng**
add checking mantine version

### CODE REVIEW

**Comment by jakeboone02** [comment]
Hey, thanks for this. I didn't realize the structure of optgroups had changed in v7. I couldn't find  anything about it in the release notes except a vague note about using the new `Combobox` component instead of `Select`.

I can help out with this PR if you're struggling with TypeScript types. They're a little weird in this library, especially the upcoming v7 stuff.

**Comment by jakeboone02** [comment]
One more thing: you don't need the version detection code or the code to support the old structure. RQB v7 will already require Mantine >= 7, so it's implicit that it should use the new structure.

**Comment by dubbofeng** [comment]
Thank you very much, I am actually trying to fix the mantine V6 select group issue. I have a project that is using mantine V6, and trying to group the select options.

**Comment by jakeboone02** [comment]
I've fixed this for v7 in b70b21358c8683e2fe8db49858e049a1408d370c, which will be merged as part of #595.

**Comment by jakeboone02** [comment]
Closing since this is fixed in v7.

**Pull request closed without merging**
