### PR TITLE
Fix react-querybuilder as an npm package / react component

### PR DESCRIPTION
**Pull request by mrvicadai**

### CODE REVIEW

**Comment by pavanpodila** [comment]
Hi @mrvicadai, Thanks for this wonderful PR. Before I merge could you please fix the failing tests. Looks good otherwise!

**Comment by pavanpodila** [comment]
@mrvicadai Also curious why you have used fixed versions on NPM packages instead of a shrinkwrap?

**Comment by pavanpodila** [comment]
@mrvicadai Still having failing tests. The removal of `lodash` looks good! Didn't realize the only use case was for `uniqueId`.

**Comment by mrvicadai** [comment]
@pavanpodila thanks for the prompt response! I'll work on fixing the tests soon;
w.r.t. the fixed version, I've encounter numerous cases when a slight change in `react` and `react-dom` version could result in some weird error. (such as using the package along with `material-ui` or `react-bootstrap`). So I guess explicitly specify version could help mitigate such issues.
I'll pin you again once the tests are fixed!

**Comment by mrvicadai** [comment]
btw, would shrinkwrap bring some additional benefits for locking down the versions? What would the eventual `package.json` look like? @pavanpodila

**Comment by pavanpodila** [comment]
Package.json would have the loose version with the `^` prefix. However, creating the shrinkwrap.json would lock down the versions. `npm install` would then only install the versions in shrinkwrap.

I see your point about version conflicts with react and other libs. It has happened to me as well. But its worth a shot. Also worth looking at yarn to see if yarn.lock can solve the version lock use case.

**Comment by mrvicadai** [comment]
ahh, it's nice to know `yarn.lock` can do just that, thanks for the tips!
btw looks like the test just went green, lemme know if this is good to go.

**Comment by pavanpodila** [comment]
@mrvicadai Still failing :-(

**Comment by mrvicadai** [comment]
looks like the removal of some code caused the decrease in coverage. Any tips on which tests can be improved?

**Comment by pavanpodila** [comment]
I think it has to do with the way you are constructing the query: https://codecov.io/gh/sapientglobalmarkets/react-querybuilder/compare/8655e26c5c4766119fdb01af0eb4ce7f9b001266...b60034e34776e8010b1d8a88b1988d2406eb5c3f 

Look at line 260

**Comment by pavanpodila** [comment]
Looks like `webpack-dev-server` also has an updated version: https://github.com/webpack/webpack-dev-server/releases/tag/v2.2.0-rc.0

**Comment by mrvicadai** [comment]
sweet, I'll look into, thanks!

**Comment by shellyjindal10** [comment]
@pavanpodila and @mrvicadai : Can you guys help merge this PR ? this is a required fix to use this library ... i am still getting the error ***Uncaught ReferenceError: React is not defined*** Thanks in advance ..

**Comment by pavanpodila** [comment]
@shellyjindal10 Can you use this commit (https://github.com/sapientglobalmarkets/react-querybuilder/pull/19/commits/cbcb605fb5c8c8edfc8d10f4f3faf537b099a19b) until @mrvicadai fixes the Code Coverage?

**Comment by mrvicadai** [comment]
I'll put this on my agenda and get it done soon. was really busy last few weeks :)

**Pull request merged**
