### PR TITLE
Updated AntD Value Select to default to search by label

### PR DESCRIPTION
**Pull request by A-EbrahimRSA**
Updated the AntD Value Select to use the updated format. This allows the usage of filtering via the "label" prop instead of the value prop as previously.

Additionally, I've made the value select by default allow for searching. I've done this in the interest of aligning the features of each styling library since several of the other design libraries have searching a value select defaulting to enabled. 

I've also noted some funky notes on a type. I'm unsure what the correct value should be and as such I've just added a comment to highlight the issue.

Whilst running the `bun checkall` command I get the following error:

```bash
[antd] @react-querybuilder/antd build: [⚛️ React Compiler] 9 files changed in 1149 ms
[antd] @react-querybuilder/antd build: [⚛️ React Compiler] 8 files changed in 1194 ms
[antd] @react-querybuilder/antd build: undefined
[antd] @react-querybuilder/antd build: [⚛️ React Compiler] 9 files changed in 898 ms
[antd] @react-querybuilder/antd build: [⚛️ React Compiler] 9 files changed in 1378 ms
[antd] @react-querybuilder/antd build: [⚛️ React Compiler] 9 files changed in 3186 ms
[antd] @react-querybuilder/antd build: Exited with code 1
[antd] error: script "build:antd" exited with code 1
[antd] bun run build:antd stopped at 2024-12-14 19:22:49.430 after 11,481ms
[antd] bun run build:antd exited with code 1
```

I also get the same error for all the other packages except rqb and I'm unsure why this is happening since I haven't changed any other files :0

### CODE REVIEW

**Comment by jakeboone02** [comment]
I'm not sure what the build error you're getting locally is. Try `cd packages/antd` and run `bun run build` from there to avoid the elision that hides the real errors.

To fix the Prettier issue, copy the `.prettierignore` file from #820.

**Comment by A-EbrahimRSA** [comment]
I've added the full console output below displaying the error when running `bun run build` inside the `packages/antd` dir.
```bash
PS C:\Projects\react-querybuilder\packages\antd> bun run build
$ bunx --bun tsup
CLI Building entry: {"react-querybuilder_C:\\Projects\\react-querybuilder\\packages\\antd":"src/index.tsx"}
CLI Using tsconfig: tsconfig.json
CLI Building entry: {"react-querybuilder_C:\\Projects\\react-querybuilder\\packages\\antd.legacy-esm":"src/index.tsx"}
CLI Using tsconfig: tsconfig.json
CLI Building entry: {"react-querybuilder_C:\\Projects\\react-querybuilder\\packages\\antd.production":"src/index.tsx"}
CLI Using tsconfig: tsconfig.json
CLI Building entry: {"react-querybuilder_C:\\Projects\\react-querybuilder\\packages\\antd.cjs.development":"src/index.tsx"}
CLI Using tsconfig: tsconfig.json
CLI Building entry: {"react-querybuilder_C:\\Projects\\react-querybuilder\\packages\\antd.cjs.production":"src/index.tsx"}
CLI Using tsconfig: tsconfig.json
CLI tsup v8.3.5
CLI Using tsup config: C:\Projects\react-querybuilder\packages\antd\tsup.config.ts
CLI tsup v8.3.5
CLI Using tsup config: C:\Projects\react-querybuilder\packages\antd\tsup.config.ts
CLI tsup v8.3.5
CLI Using tsup config: C:\Projects\react-querybuilder\packages\antd\tsup.config.ts
CLI tsup v8.3.5
CLI Using tsup config: C:\Projects\react-querybuilder\packages\antd\tsup.config.ts
CLI tsup v8.3.5
CLI Using tsup config: C:\Projects\react-querybuilder\packages\antd\tsup.config.ts
CLI Target: esnext
CLI Target: es2017
ESM Build start
CLI Target: esnext
CJS Build start
CLI Target: esnext
CJS Build start
CLI Target: esnext
ESM Build start
CLI Cleaning output folder
ESM Build start
Dynamic import can only be transformed when transforming ES modules to AMD, CommonJS or SystemJS.
[⚛️ React Compiler] 9 files changed in 680 ms
[⚛️ React Compiler] 10 files changed in 257 ms
undefined
[⚛️ React Compiler] 10 files changed in 357 ms
[⚛️ React Compiler] 10 files changed in 325 ms
[⚛️ React Compiler] 10 files changed in 253 ms
error: script "build" exited with code 1
PS C:\Projects\react-querybuilder\packages\antd> 
```

I also get the same error when running the command within any of the other styling packages.

In the main rqb package, I see the `Dynamic import ...` message however the build continues.

I've also tried `bun install --frozen-lockfile` to try and see if that resolves anything but to no avail :(

**Comment by A-EbrahimRSA** [comment]
@jakeboone02 do you maybe have any thoughts on my previous message? No worries if not yet I know its holiday season so I'm not too rushed for these changes as well

**Comment by jakeboone02** [comment]
> @jakeboone02 do you maybe have any thoughts on my previous message? No worries if not yet I know its holiday season so I'm not too rushed for these changes as well

Yeah, actually I was going to get back to you once I merged #820 since I think it fixes some build issues that are still in `main`. I'll probably merge that today, then you can merge `main` into your branch and see it that helps. One note: I switched to [Bun's text lockfile](https://bun.sh/blog/bun-lock-text-lockfile) so you'll need to run `bun upgrade` to handle it.

**Comment by A-EbrahimRSA** [comment]
> > @jakeboone02 do you maybe have any thoughts on my previous message? No worries if not yet I know its holiday season so I'm not too rushed for these changes as well
> 
> Yeah, actually I was going to get back to you once I merged #820 since I think it fixes some build issues that are still in `main`. I'll probably merge that today, then you can merge `main` into your branch and see it that helps. One note: I switched to [Bun's text lockfile](https://bun.sh/blog/bun-lock-text-lockfile) so you'll need to run `bun upgrade` to handle it.

Okay thanks :) I've added a notification on merging #820 so whenever you get round to that I'll have a look at updating my PR

**Pull request closed without merging**
