### PR TITLE
JsonLogic and SpEL export formats

### PR DESCRIPTION
**Pull request by jakeboone02**

### CODE REVIEW

**Comment by fasiha** [comment]
Just curious, when will this be published to npm? I'd love to try this out, I'd never heard of JsonLogic and it seems like a really convenient way to run rules on the frontend 👀!

**Comment by jakeboone02** [comment]
Soon! Maybe even later today, as v4.4.1. Have to do a little more real-world testing first.

**Comment by jakeboone02** [comment]
@fasiha I just published [v4.4.1](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.4.1).

**Comment by fasiha** [comment]
I was digging for why `formatQuery` with `format: "jsonlogic"` and a `valueProcessor` doesn't call that `valueProcessor`, is that because of this:
https://github.com/react-querybuilder/react-querybuilder/blob/431673e67c0ebde66be797b44511321c1bb72de2/packages/react-querybuilder/src/utils/formatQuery/formatQuery.ts#L447

That is, the `else if (format === 'jsonlogic')` block never calls `valueProcessorInternal` (which wraps the `valueProcessor` I pass in), unlike the other `format`s.

Is it intended that jsonlogic output precludes value processing? Thanks for all your time today!!

**Comment by jakeboone02** [comment]
Yes, that's correct. The "jsonlogic" format ignores the `valueProcessor` option (for now -- I'll probably change that once `valueProcessor` can accept a full rule object).

**Pull request merged**
