### PR TITLE
Chakra v3 support

### LINKED ISSUE #802: Support Chakra v3
- [Migration guide](https://www.chakra-ui.com/docs/get-started/migration)
- [Vite guide](https://www.chakra-ui.com/docs/get-started/frameworks/vite)
- [StackBlitz playground](https://stackblitz.com/edit/chakra-ui-v3)

ref #801

### PR DESCRIPTION
**Pull request by abrenoch**
Copy of #804

Closes #802

### CODE REVIEW

**Comment by jakeboone02** [comment]
Looks like I can edit this one. Thanks!

**Comment by jakeboone02** [comment]
Well, it _says_ I can push to it on the PR, but it won't actually let me push.

image

```
> git push abrenoch HEAD:chakra-v3
remote: Permission to abrenoch/react-querybuilder.git denied to jakeboone02.
fatal: unable to access 'https://github.com/abrenoch/react-querybuilder/': The requested URL returned error: 403
```

Could there be a setting on your account or the fork that might be causing that?

**Comment by jakeboone02** [comment]
I wonder if it's because this PR's branch was forked from that org branch and not directly from this repo:

image

**Comment by abrenoch** [comment]
Possibly! How silly. I tried adding you as a collaborator to my repo if that helped?

**Comment by jakeboone02** [comment]
> Possibly! How silly. I tried adding you as a collaborator to my repo if that helped?

Yep, that did it. Thanks!

**Comment by jakeboone02** [comment]
@abrenoch I updated all the "other" stuff like the dev page, example, and website demo. Want to give 'em a whirl?

- [CodeSandbox example](https://codesandbox.io/p/devbox/pq4zqv?file=%2Fsrc%2FApp.tsx)
- [Website demo](https://deploy-preview-805--react-querybuilder.netlify.app/demo/chakra)

I'm still not sure how I'm going to handle dual compatibility with v2, but let me know what you think of these changes for v3.

**Comment by abrenoch** [comment]
@jakeboone02 Passes the sniff test for me, I think you nailed it!

**Comment by jakeboone02** [comment]
Great! I'll merge this once I figure out what to do about v2 going forward.

**Comment by jakeboone02** [comment]
Hey, one question: Do you think the "snippets" are really necessary in the case of a library like this? I know it's the recommended way in the Chakra docs, but they're not really re-used in the way an application would re-use them. Each snippet is only ever imported once within the package (so the props are always the same), and I feel like the snippet code could just be integrated directly into the existing component files or even removed completely in some cases. For example, I don't see a need for the "loading" render paths in `snippets/button`, so we could just use `Button` directly from `@chakra-ui/react` in `ChakraActionElement` (like `ChakraShiftActions` already does).

**Comment by abrenoch** [comment]
> Hey, one question: Do you think the "snippets" are really necessary in the case of a library like this? I know it's the recommended way in the Chakra docs, but they're not really re-used in the way an application would re-use them. Each snippet is only ever imported once within the package (so the props are always the same), and I feel like the snippet code could just be integrated directly into the existing component files or even removed completely in some cases. For example, I don't see a need for the "loading" render paths in `snippets/button`, so we could just use `Button` directly from `@chakra-ui/react` in `ChakraActionElement` (like `ChakraShiftActions` already does).

I can see this making sense, especially in the case of `Button` which chakra still seems to supply a more primitive version of. I was thinking about that when making the changes, but since I'm not *super* familiar with this library I wanted to keep the chakra component APIs as close to what they originally where for compatibility reasons. I think that would be a sensible approach!

**Comment by jakeboone02** [comment]
Thanks for the feedback. After looking it over a little more, I decided to stick with the snippets after all, except `button` and the unused `field` snippet.

**Comment by jakeboone02** [comment]
@all-contributors please add @abrenoch for code

**Pull request merged**
