### PR TITLE
Support TypeScript <4.5

### PR DESCRIPTION
**Pull request by jakeboone02**

### CODE REVIEW

**Comment by duhaime** [comment]
@jakeboone02 I'm seeing a bunch of [failing typechecks](https://gist.github.com/duhaime/17cb942b612c688d3669784874130ce9) that may be related to this MR? 

Do you know what might be causing this, or how I can resolve these errors? Any pointers would be very helpful!

This is on react-querybuilder@4.3.1

**Comment by jakeboone02** [comment]
Hi, @duhaime. Can you provide a repo that reproduces the errors? Also, what TS version are you using?

**Comment by jakeboone02** [comment]
@duhaime I'm trying to reproduce the errors in the TS playground, but not having any luck.  The errors in your gist appear to show an issue with actual TS syntax, which is weird because it wouldn't compile if that was true.

I don't know if this matters, but I did notice that something changed between TS 4.0 and 4.1 that affected how the `AnyCase` type is interpreted. In 4.1 it uses the template strings as written in the original source. But in 4.0 and below, the template strings get widened to `string`, which makes `AnyCase<'NOT'>`, for example, get widened all the way to `any` instead of `'NOT' | 'NOt' | 'NoT' | ...`.

[4.0 playground link](https://www.typescriptlang.org/play?ts=4.0.5#code/JYWwDg9gTgLgBAbzgQQHYE8DCBDAzgUzgF84AzKCEOAcin2wGMYBaARwFd8p0Ajd4ADYATLtQDcAKAkMIqXPGwYcBAHIB5ACoAuFErz4APNXUbqAPjgBeGiogxxU-AA9IsRHEVZ9J4pKA)

image

[4.1 playground link](https://www.typescriptlang.org/play?ts=4.1.5#code/JYWwDg9gTgLgBAbzgQQHYE8DCBDAzgUzgF84AzKCEOAcin2wGMYBaARwFd8p0Ajd4ADYATLtQDcAKAkMIqXPGwYcBAHIB5ACoAuFErz4APNXUbqAPjgBeGiogxxU-AA9IsRHEVZ9J4pKA)

image

Edit: of course [TS introduced template literal types in 4.1](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types), but it's interesting that pre-4.1 falls back to `string` when it sees a template literal.

**Comment by duhaime** [comment]
Hello! We're on TS 4.2.4. I can try to put together a fiddle in the coming days if you can't reproduce this yet!

**Comment by jakeboone02** [comment]
Yeah, please do. I'd also be curious if you can get the same errors to appear using `typescript@>=4.5`, since that [uses a different set of types files](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/react-querybuilder/package.json#L8-L14).

**Pull request merged**
