### PR TITLE
Proposal: omit moment from antd build

### LINKED ISSUE #353: "Module not found: Error: Can't resolve './locale'" warning when building with Ant Design components
I'm sorry to risk opening a ticket here for this when I'm not 100% sure it's an issue with react-querybuilder 🙇 please feel free to close if this isn't your problem!

I'm encountering a warning
```
WARNING in ./node_modules/@react-querybuilder/antd/dist/index.es.js 1941:6-40
Module not found: Error: Can't resolve './locale' in '/home/afasih/Documents/my-app/node_modules/@react-querybuilder/antd/dist'
```
when building my react-querybuilder project, and as my CI (continuous integration) treats warnings as errors, I'm looking for how to fix this.

## Reproduction steps
```
npx create-react-app my-app --template typescript
cd my-app
npm i --save react-querybuilder @react-querybuilder/antd @ant-design/icons antd
```
In App.tsx, replace the body with
```ts

import { antdControlElements } from "@react-querybuilder/antd";
import { QueryBuilder, RuleGroupType } from "react-querybuilder";
import "react-querybuilder/dist/query-builder.css";
import "antd/dist/antd.compact.css";

const fields = [
  { name: "firstName", label: "First Name" },
  { name: "lastName", label: "Last Name" },
];

const App = () => {
  const [query, setQuery] = useState<RuleGroupType>({
    combinator: "and",
    rules: [],
  });

  return (
    <QueryBuilder
      fields={fields}
      query={query}
      onQueryChange={(q) => setQuery(q)}
      controlElements={antdControlElements}
    />
  );
};
```
Then run `npm run start`

(This actually might produce some other warnings too, but the one I'm encountering in my application is the `Module not found: Error: Can't resolve './locale'`.)

## Discussion
Searching the web shows that this surfaced in ~2020 due to an issue with Moment: cf.,
- https://github.com/ant-design/ant-design/issues/23823 and
- upstream https://github.com/moment/moment/issues/5472

These appear to have been fixed upstream, but I noticed that react-querybuilder's Ant package uses Ant [4.17.3](https://github.com/ant-design/ant-design/releases/tag/4.17.3) from about six months ago (in [package.json](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/antd/package.json#L31)) and, I know it's a stretch but I wonder if the `antd` bundled with this package is somehow either installing an old Moment, or if there's some other explanation/workaround?

Thanks for your help!

### PR DESCRIPTION
**Pull request by fasiha**
Fixes #353, please see discussion there.

### CODE REVIEW

**Comment by jakeboone02** [comment]
Thanks for submitting this, @fasiha. Can you try the [`antd` codesanbox](https://codesandbox.io/s/react-querybuilder-antd-example-sw8n3n) based on this PR and see if it solves the issue you raised in #353?

**Comment by jakeboone02** [comment]
> Thanks for submitting this, @fasiha. Can you try the [`antd` codesanbox](https://codesandbox.io/s/react-querybuilder-antd-example-sw8n3n) based on this PR and see if it solves the issue you raised in #353?

Sorry, wrote this comment before I saw your last one on #353! This looks reasonable so I'll go ahead and merge.

Just FYI, I wasn't planning on putting a new version out until #340 was resolved. That would also mean a major version bump. Is this issue critical for you? I can squeeze in a v4.5.2 with this fix if necessary.

**Comment by jakeboone02** [comment]
@all-contributors please add @fasiha for code

**Comment by fasiha** [comment]
Thank you so much!!!

> Is this issue critical for you? I can squeeze in a v4.5.2 with this fix if necessary.

My lovely devops team would definitely love it if I resolved this issue for them sooner than later 😁 but we have a workaround for now so please don't push yourself?

**Comment by jakeboone02** [comment]
Sure, I'll see what I can do

**Comment by jakeboone02** [comment]
[v4.5.2](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.5.2) was released earlier today with this fix included. :)

**Pull request merged**
