### PR TITLE
Make `formatQuery` output for "mongodb" type `JSON.parse`-able

### LINKED ISSUE #256: Query Formatter for Mongo seem to be not parsable into js object
Hi

At the moment queries formatted with `const testMongoQueryStr = formatQuery(item, 'mongodb')` can not be further parsed with JSON.parse() i.e `const mongoQueryParams = JSON.parse(testMongoQueryStr )`  and  so are throwing an error if you would try to use it as a part of mongoDb query.

As an example please take a look at this test in the repo. As far as I understand this needs to be an object not a string and also this string needs to be valid for JSON.parse() : https://github.com/react-querybuilder/react-querybuilder/blob/e126531f2e49f90e54319e1a9cfefd35a950be96/packages/react-querybuilder/src/utils/__tests__/formatQuery.test.ts#L290

Additionally any numeric fields are formatted as strings like so using the `formatQuery(item, 'mongodb')`:  `"{$and:[{testNumInput:{$lte:\"67\"}}]}"` instead of: `"{$and:[{"testNumInput":{$lte:67}}]}"`   and $lte will not work as expected because strings will not be properly compared against numbers.

Here is an example of properly formatted mongodb query:

`const cursor = db.collection('inventory').find({
  status: 'A',
  qty: { $lt: 30 }
});`

at: https://docs.mongodb.com/manual/tutorial/query-documents/#specify-and-conditions

I would expect that formatQuery should return the following in that case: `'{"status":"A","qty":{"$lt":30}}'`  and instead it returns this: `'{status:"A",qty:{$lt:"30"}}'` which can not be parsed into js object

### PR DESCRIPTION
**Pull request by mylawacad**
Quick fix making the resulting query string to be a valid JSON

Fixes #256

### CODE REVIEW

**Comment by jakeboone02** [comment]
@mylawacad Something's wrong with the prettier action. Could you run prettier manually and push again?

Also, you'll need to convert all the regex operators from `/pattern/` to `{"$regex":"pattern"}` as mentioned in [this comment](https://github.com/react-querybuilder/react-querybuilder/issues/256#issuecomment-999769028).

**Comment by mylawacad** [comment]
> convert all the regex operators from `/pattern/` to `{"$regex":"pattern"}` as mentioned in [this comment](https://github.com/react-querybuilder/react-querybuilder/issues/256#issuecomment-999769028)

Thank you @jakeboone02

**Comment by jakeboone02** [comment]
Alright, it's close, but not quite there yet.  The [`$regex` syntax](https://docs.mongodb.com/manual/reference/operator/query/regex/) requires an object with a `"$regex"` member whose value is the pattern. Your current implementation just uses a string, which is indicating you want records where the field matches that value exactly.

Here's an example of what needs to be changed:

```diff
             } else if (rule.operator === 'contains') {
-              return `{"${rule.field}":"${rule.value}"}`;
+              return `{"${rule.field}":{"$regex":"${rule.value}"}}`;
             } else if (rule.operator === 'beginsWith') {
-              return `{"${rule.field}":"^${rule.value}"}`;
+              return `{"${rule.field}":{"$regex":"^${rule.value}"}}`;
             } else if (rule.operator === 'endsWith') {
-              return `{"${rule.field}":"${rule.value}$"}`;
+              return `{"${rule.field}":{"$regex":"${rule.value}$"}}`;
```

That is not a comprehensive example -- there are more lines to change than those indicated.

**Comment by mylawacad** [comment]
Hi @jakeboone02   I propose to omit `$regex` member so far because MongoDb allows this as of now:
https://docs.mongodb.com/manual/reference/operator/query/eq/#regex-match-behaviour

image


What do you think?

**Comment by jakeboone02** [comment]
If you mean to use raw regexes instead, I don't think that will work with `JSON.parse`.

Edit: confirmed. `JSON.parse('{"field":/pattern/}'}` results in an error.

**Comment by jakeboone02** [comment]
I think this is good for now, so I'm going to go ahead and merge.

**Comment by mylawacad** [comment]
> If you mean to use raw regexes instead, I don't think that will work with `JSON.parse`.
> 
> Edit: confirmed. `JSON.parse('{"field":/pattern/}'}` results in an error.

Not exactly, the strings containing a regular exression are recognized by MongoDb as well: 
https://docs.mongodb.com/manual/reference/operator/query/regex/#definition

image

But I already made another commit a while ago with $regex member added because after looking at resulting code I discovered that with $regex it is much more readable.  

P.S  Besides the 'contains'  regex is bein recognized as a simple string :p

Thank you for merging and your help!

**Comment by mylawacad** [comment]
@jakeboone02   chances this merge could receive a minor version tag please? Would be great to be able to add this to my app package json as a versioned dependency please

**Comment by jakeboone02** [comment]
@mylawacad Do you mean as `v4.0.0-beta.8`? Making a `v3.12.2` (or `v3.13.0`) at this point would be difficult.

**Comment by mylawacad** [comment]
> @mylawacad Do you mean as `v4.0.0-beta.8`? Making a `v3.12.2` (or `v3.13.0`) at this point would be difficult.

Thank you @jakeboone02  please  make it `v4.0.0-beta.8` then if possible

**Comment by jakeboone02** [comment]
Sure, no problem. Probably sometime tomorrow, but it's Christmas Eve here in the States so no promises... :christmas_tree:

**Comment by mylawacad** [comment]
Sure, no problem.  Merry Christmas and happy holidays!

**Comment by jakeboone02** [comment]
@mylawacad - I just published [v4.0.0-beta.8](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.8). Let me know if it works for you.

**Comment by mylawacad** [comment]
@jakeboone02  New version got installed without any issues.  Thank you and have a great holiday!

**Pull request merged**
