### PR TITLE
Support chakra v3

### LINKED ISSUE #802: Support Chakra v3
- [Migration guide](https://www.chakra-ui.com/docs/get-started/migration)
- [Vite guide](https://www.chakra-ui.com/docs/get-started/frameworks/vite)
- [StackBlitz playground](https://stackblitz.com/edit/chakra-ui-v3)

ref #801

### PR DESCRIPTION
**Pull request by abrenoch**
Wanted to get the ball rolling on supporting chakra-ui v3!

There have been some changes in v3 that removed some of the built-in components chakra originally offered in favor of a snippet based system. In this approach I premade the snippets in the `packages/chakra/src/snippets` directory, and replaced the relevant `@chakra/icons` (now deprecated) with equivalents from `react-icons`.

This PR needs some work still, but wanted to open a draft to determine if this is the route the maintainers would like to move in.

Closes #802

### CODE REVIEW

**Comment by jakeboone02** [comment]
Oh wow, thank you so much! I was looking at this just a couple of hours ago and absolutely dreading all the churn, but it looks like you've already done a lot of the work!

I'll take a closer look later today. One question after a _very_ quick glance: does the Chakra CLI package need to be in the dependencies?

The biggest question for this library is going be how to support v2 and v3 simultaneously. There are a few options but none of them seem simple or easy from a maintenance perspective. I could fork the package and have a separate `@react-querybuilder/chakra-v2` package, or maintain a git branch that publishes to a "v2" dist-tag on npm. If you have any other good ideas, let me know.

**Comment by abrenoch** [comment]
> Oh wow, thank you so much! I was looking at this just a couple of hours ago and absolutely dreading all the churn, but it looks like you've already done a lot of the work!
> 
> I'll take a closer look later today. One question after a _very_ quick glance: does the Chakra CLI package need to be in the dependencies?
> 
> The biggest question for this library is going be how to support v2 and v3 simultaneously. There are a few options but none of them seem simple or easy from a maintenance perspective. I could fork the package and have a separate `@react-querybuilder/chakra-v2` package, or maintain a git branch that publishes to a "v2" dist-tag on npm. If you have any other good ideas, let me know.

Glad to help out! This library has saved us (and I'm sure many others) a lot of time, so the least I can do is try to give back a little.

I hear you on the changes, we have a medium sized app that will need quite the refactor to work with v3. But that would start with getting our chakra related dependencies updated first, so here I am! The `chakra-cli` package is not needed, must have slipped in there when I was getting the snippets installed.

Supporting both versions does sound like a pain. I'm not sure I'm familiar enough with `import` voodoo to work out a unified solution (if that could even be done). Treating v2 & v3 as separate packages *seems* like it would be the most manageable approach though it may demand a little more maintenance in the long term.

**Comment by jakeboone02** [comment]
Could you allow changes from maintainers on your PR branch? I can rebase/merge from `main` for you if you want, and we can collab from there.

**Comment by abrenoch** [comment]
@jakeboone02 Would be glad to - however the checkbox to "allow edits by maintainers" isn't showing up anywhere in this PR (or when editing it)... Or am I mistaken about where to find that?

**Comment by jakeboone02** [comment]
> @jakeboone02 Would be glad to - however the checkbox to "allow edits by maintainers" isn't showing up anywhere in this PR (or when editing it)... Or am I mistaken about where to find that?

I think there should be a checkbox at the bottom of the right-hand sidebar, around here:

image

**Comment by abrenoch** [comment]
Thats where I was expecting it too, but its not there for me at the moment:
image

**Comment by jakeboone02** [comment]
I marked the PR as ready for review, maybe it's there now?

**Comment by abrenoch** [comment]
Unfortunately not - It *may* be because the PR is coming from an organization GH account rather than a personal one... I'll try a PR from my personal account

EDIT: That seems to be the case - I'll close this PR

**Pull request closed without merging**
