### PR TITLE
update query prop if a new one is passed in

### PR DESCRIPTION
**Pull request by BradfordMedeiros**
Addresses #30 

Update the root state when a new query prop is passed in.
From the user perspective, this allows the user to utilize this query prop, and the onQueryChange callback function to essentially move the state of the query out of this component. 

Just for insight into my usage: My personal use case of this is with redux in which i save multiple query types.  With the query prop, I am able to select a new query from the drop-down, and which eventually gets set as a prop of this query.  From there the user can edit the populated query fields in-place. 
I use the on query change to get the query itself and that hooks up into state, and eventually redux. 

I also built the dist files using the command  `npm run dist`.

### CODE REVIEW

**Comment by pavanpodila** [comment]
@BradfordMedeiros this looks good. I only need a test that will ensure this use case is covered. I can then merge it in.

**Comment by loris** [comment]
@BradfordMedeiros @pavanpodila Needs this PR merged with the same use case you are describing. Is there any blocker? Can I help?

**Comment by chinmaydalvi** [comment]
@BradfordMedeiros  @pavanpodila 
Currently test cases are failing and also have some conflicts.
can we merge this functionality  as soon as possible?

**Comment by pavanpodila** [comment]
Hi @chinmaydalvi, looks like there is a merge conflict. Can merge after resolution

**Comment by chinmaydalvi** [comment]
Hi @BradfordMedeiros 
Can you please resolve merge conflicts as it is crucial bug and get it merge as soon as possible.

**Comment by miphe** [comment]
This was addressed in #67 - closing this PR. If there's more work that should be merged from here, please re-open it.

**Pull request closed without merging**
