### PR TITLE
Fixed a rule default value on add/change

### LINKED ISSUE #109: Value is not getting reflected in Query
I am using query builder as mentioned in Live Demo by passing functions getOperators, getValueEditorType, getInputType and getValues. Everything is working fine except query. When value field is of number, date, radio button or Select then Value is not getting reflected in generated Query. 
Please help.

### PR DESCRIPTION
**Pull request by xxsnakerxx**
This PR fixes https://github.com/sapientglobalmarkets/react-querybuilder/issues/109

### CODE REVIEW

**Comment by jakeboone02** [comment]
Thanks!

**Comment by xxsnakerxx** [comment]
@jakeboone02 Could you also build the dist with these changes and publish them to npm?!

**Comment by jakeboone02** [comment]
@xxsnakerxx - [done](https://github.com/sapientglobalmarkets/react-querybuilder/releases/tag/v3.0.2).

**Comment by xxsnakerxx** [comment]
Thank you! 👍🏻

**Pull request merged**
