### PR TITLE
Changes and tests for #30 to handle updates to query prop

### PR DESCRIPTION
**Pull request by muralikg**
Added tests for changes done by @BradfordMedeiros in a different pull request.

### CODE REVIEW

**Comment by pavanpodila** [comment]
@muralikg looks like there is a drop in coverage. Could you please ensure the tests are covering at least 70% of the code.

**Comment by muralikg** [comment]
@pavanpodila I have fixed my test to bring the coverage above 70% please let me know if you need any changes.

**Comment by muralikg** [comment]
@pavanpodila Any ideas on testing the async behavior of setState?
I had to write some ugly test case when code flows through the `if` condition. I am not sure how to test for the case when the `if` condition is skipped.

**Comment by pavanpodila** [comment]
closing due to inactivity

**Pull request closed without merging**
