### PR TITLE
Reset value on operator change

### LINKED ISSUE #132: Add option to reset value on operator change
Here is the problem that I have faced:

Let's say we have a field named hobbies, which can be ["Football", "Soccor", "Fishing", "Programming", "Filmmaking"]

Now, I want there to be two operators possible on this field:
{name: '=', label: 'is'} and {name: 'beginsWith', label: 'begins with'}

I have set the is operator to return a "select" valueEditor, and the beginsWith to return a "text" valueEditor.

Here is the bug that would occur:
Let's say I type "F" while the "beginsWith" operator is set, then change the operator back to "is" (which will display a select element now). The rule's value would still remain as "F" in the query, until the user changes the select dropdown's value.

I suppose if this functionality exists, there should also be functionality to allow the value to not be reset, if both operators resolve to the same ValueEditor type. Let me know what you think of this.

I left a PR up with a proposed solution, but it stayed up for over a month without feedback. Now that it is out of date, I decided to close it.

Please let me know if this option is something that would be welcome in `react-querybuilder`; I would be happy to create another PR for it.

### PR DESCRIPTION
**Pull request by artenator**
This fixes #132 

I think we should also consider having another option to only reset the operator when the `valueEditor` has changed. Let me know what you think of this.

### CODE REVIEW

**Comment by jakeboone02** [comment]
@artenator can you resolve the conflicts with this PR?  I'll merge it once that's done.

**Comment by artenator** [comment]
> @artenator can you resolve the conflicts with this PR?  I'll merge it once that's done.

Sorry for the delayed response. If this hasn’t been taken care of already, I can get it done this week within a couple days. Please let me know. Thanks!

**Comment by jakeboone02** [comment]
Go for it!  👍

**Comment by jakeboone02** [comment]
@artenator looks like you'll need to update the tests to keep them at 100%.

**Comment by artenator** [comment]
@jakeboone02 
Done. Please let me know what you think. 

I think that resetting the value only when the `valueEditor` is different could be a possible next step/improvement for this feature. This might be undesired behavior in some cases, so we could add another option for this. 

However, I'm not sure if that is something we also want to include in this specific PR. Looking forward to hearing your thoughts. Thanks! 😎

**Comment by jakeboone02** [comment]
@artenator I think that's a good idea and would definitely consider a PR to implement that functionality.  Thanks!

**Pull request merged**
