### PR TITLE
fix: $regex does not accept single characters

### PR DESCRIPTION
**Pull request by weiliddat**
Problem: it's not possible to import a MongoDB query like `{ "foo": { "$regex": "A" }}`.

Reproduce on [playground](https://react-querybuilder.js.org/demo#s=eJxdkk1vwjAMhv9LziCN0SHgxoeYJrGijd2mHdzGLdlC3CXOEEL896UftMAlUp7Xdl7bOYlfj%2FYopieR0j5RBpismAowUvSE9RqdmH6ehJIBjuApSnAw7I%2FHQ%2BhHk%2BGgD6Ns1J9EUfaQPibDUTQOWZlCXYZnyjqOYY%2BBUYG2KZ2SYVDGBfoH2uOWvE0xCNXtQsN9K85f515t8GVRWrz4KTEVrChUCdjt6LBo3bs58gHRvNfBGWiHvSomJv6gPNd4QxeaDM49c1XtSlhT%2BnPPLTrkjVmVLS52YPJQi63vlE3T6EVs8sAzbVFjyqt6OnVShzftgBpFyrKBD4rx8GzJF52HMB8lgfGt3lxDlZFYYDgMX82ilbVy7GZuZi0cO4oGEo1LC%2FnMyKWlolWkcqUkO4CJz19Jdj0VYB3Gfp%2Fg1Tvf3rEKP0Cu4UiebwY6t2DS3d1StjuV8SxtllkJYbuOj%2BWawqsZeM3i%2FA%2B4FPED) when you reimport the MongoDB query it returns `{ "$expr": true }`.

### CODE REVIEW

**Comment by jakeboone02** [comment]
@all-contributors please add @weiliddat for code, tests

**Comment by jakeboone02** [comment]
@weiliddat - good catch. Thanks!

**Comment by weiliddat** [comment]
You're welcome 😊

**Comment by jakeboone02** [comment]
This is included in [v7.5.2](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v7.5.2). Actually, it's the _only_ thing included in 7.5.2 lol.

**Pull request merged**
