### PR TITLE
Fix json_without_ids implementation to not strip non-id keys

### PR DESCRIPTION
**Pull request by zachblume**
Implement json_without_ids such that it strips 'id' key instead of whitelisting 'acceptable' keys to avoid recursively key-stripping client-provided objects

### CODE REVIEW

**Comment by jakeboone02** [comment]
I like this, but I'll have to think about it because it would be an unexpected change in behavior. I wonder if we shouldn't just create a new export type that does this (even if the name of this one is more appropriate).

Also, you need to run `bun pretty-print`.

**Comment by zachblume** [comment]
I'm happy to break this off with a different key to avoid breaking change if thats better. thx for pretty-print advice

**Comment by zachblume** [comment]
I will say however that this was something that affected me and TBH the undocumented behavior of _without_ids destroying all keys not named was odd and buggy, so perhaps it's a (un)breaking change, but a logical one for the next major version

**Comment by jakeboone02** [comment]
> I will say however that this was something that affected me and TBH the undocumented behavior of _without_ids destroying all keys not named was odd and buggy, so perhaps it's a (un)breaking change, but a logical one for the next major version

Yeah, I understand. That's why I'm considering it. Leave it as is for now and I'll make a call soon.

**Comment by jakeboone02** [comment]
I was concerned that a breaking change like this would be disruptive, but for one thing, we've got a major version coming up soon and breaking changes are expected in major versions. For another, the existing functionality is a [one-liner](https://github.com/react-querybuilder/react-querybuilder/blob/a2bd18c44a46be85b3662aa80eecfae1dee758dd/packages/react-querybuilder/src/utils/formatQuery/formatQuery.ts#L188-L196) that could be easily replicated in userland.

I'll merge this once these changes are made:

- Along with `id`, also exclude the `path` property
- Fix failing tests, while maintaining 100% coverage

**Comment by jakeboone02** [comment]
Ugh, I didn't mean to close this. Trying to fix it now...

**Comment by jakeboone02** [comment]
I ended up creating a new PR (#642), but it does include your commits from this one. I'll add you to the contributors list, too.

**Pull request closed without merging**
